
#ifndef OHDSCANSLAVE_COMPILER_CFG_H
#define OHDSCANSLAVE_COMPILER_CFG_H

#define OHDS_CODE
#define OHDS_CONST
#define OHDS_VAR_NOINIT
#define OHDS_VAR_ZERO_INIT
#define OHDS_APPL_VAR

#endif
