

#ifdef OHDS_START_SEC_CODE
# undef OHDS_START_SEC_CODE
# define START_SEC_CODE
#endif
#ifdef OHDS_STOP_SEC_CODE
# undef OHDS_STOP_SEC_CODE
# define STOP_SEC_CODE
#endif

#ifdef OHDS_START_SEC_CONST_UNSPECIFIED
# undef OHDS_START_SEC_CONST_UNSPECIFIED
# define START_SEC_CONST_UNSPECIFIED
#endif
#ifdef OHDS_STOP_SEC_CONST_UNSPECIFIED
# undef OHDS_STOP_SEC_CONST_UNSPECIFIED
# define STOP_SEC_CONST
#endif

#ifdef OHDS_START_SEC_VAR_NOINIT_8BIT
# undef OHDS_START_SEC_VAR_NOINIT_8BIT
# define START_SEC_VAR_NOINIT_8BIT
#endif
#ifdef OHDS_STOP_SEC_VAR_NOINIT_8BIT
# undef OHDS_STOP_SEC_VAR_NOINIT_8BIT
# define STOP_SEC_VAR
#endif

#ifdef OHDS_START_SEC_VAR_NOINIT_16BIT
# undef OHDS_START_SEC_VAR_NOINIT_16BIT
# define START_SEC_VAR_NOINIT_16BIT
#endif
#ifdef OHDS_STOP_SEC_VAR_NOINIT_16BIT
# undef OHDS_STOP_SEC_VAR_NOINIT_16BIT
# define STOP_SEC_VAR
#endif

#ifdef OHDS_START_SEC_VAR_NOINIT_32BIT
# undef OHDS_START_SEC_VAR_NOINIT_32BIT
# define START_SEC_VAR_NOINIT_32BIT
#endif
#ifdef OHDS_STOP_SEC_VAR_NOINIT_32BIT
# undef OHDS_STOP_SEC_VAR_NOINIT_32BIT
# define STOP_SEC_VAR
#endif

#ifdef OHDS_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef OHDS_START_SEC_VAR_NOINIT_UNSPECIFIED
# define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif
#ifdef OHDS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef OHDS_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# define STOP_SEC_VAR
#endif

#ifdef OHDS_START_SEC_VAR_ZERO_INIT_8BIT
# undef OHDS_START_SEC_VAR_ZERO_INIT_8BIT
# define START_SEC_VAR_ZERO_INIT_8BIT
#endif
#ifdef OHDS_STOP_SEC_VAR_ZERO_INIT_8BIT
# undef OHDS_STOP_SEC_VAR_ZERO_INIT_8BIT
# define STOP_SEC_VAR
#endif

