

#ifdef RTE_START_SEC_CODE
# undef RTE_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef RTE_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef RTE_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef RTE_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_VAR_ZERO_INIT_8BIT
# undef RTE_START_SEC_VAR_ZERO_INIT_8BIT
#define START_SEC_VAR_ZERO_INIT_8BIT
#endif

#ifdef RTE_START_SEC_VAR_INIT_UNSPECIFIED
# undef RTE_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_CONST_UNSPECIFIED
# undef RTE_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_APPL_CODE
# undef RTE_START_SEC_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef RTE_STOP_SEC_CODE
# undef RTE_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef RTE_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef RTE_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef RTE_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_VAR_ZERO_INIT_8BIT
# undef RTE_STOP_SEC_VAR_ZERO_INIT_8BIT
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef RTE_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_CONST_UNSPECIFIED
# undef RTE_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef RTE_STOP_SEC_APPL_CODE
# undef RTE_STOP_SEC_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef RTE_START_SEC_COMM_APPL_CODE
# undef RTE_START_SEC_COMM_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef RTE_START_SEC_CTAPHUFTPMSDIA_APPL_CODE
# undef RTE_START_SEC_CTAPHUFTPMSDIA_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSdia_START_SEC_CODE
# undef CtApHufTPMSdia_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSdia_START_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSdia_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef CtApHufTPMSdia_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSdia_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSdia_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSdia_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSdia_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSdia_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_CTAPHUFTPMSMGR_APPL_CODE
# undef RTE_START_SEC_CTAPHUFTPMSMGR_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSmgr_START_SEC_CODE
# undef CtApHufTPMSmgr_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSmgr_START_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSmgr_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef CtApHufTPMSmgr_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSmgr_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSmgr_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSmgr_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSmgr_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSmgr_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_CTAPHUFTPMSROE_APPL_CODE
# undef RTE_START_SEC_CTAPHUFTPMSROE_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSroe_START_SEC_CODE
# undef CtApHufTPMSroe_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSroe_START_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSroe_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef CtApHufTPMSroe_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSroe_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSroe_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSroe_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSroe_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSroe_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_CTAPHUFTPMSWNH_APPL_CODE
# undef RTE_START_SEC_CTAPHUFTPMSWNH_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSwnh_START_SEC_CODE
# undef CtApHufTPMSwnh_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSwnh_START_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSwnh_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef CtApHufTPMSwnh_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSwnh_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSwnh_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSwnh_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSwnh_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSwnh_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_CTAPHUFTPMSWPA_APPL_CODE
# undef RTE_START_SEC_CTAPHUFTPMSWPA_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSwpa_START_SEC_CODE
# undef CtApHufTPMSwpa_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CtApHufTPMSwpa_START_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSwpa_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef CtApHufTPMSwpa_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSwpa_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSwpa_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSwpa_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef CtApHufTPMSwpa_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSwpa_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_CTCDHUFTPMSRFD_APPL_CODE
# undef RTE_START_SEC_CTCDHUFTPMSRFD_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef CtCdHufTPMSrfd_START_SEC_CODE
# undef CtCdHufTPMSrfd_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef CtCdHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef CtCdHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef CtCdHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef CtCdHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_START_SEC_NVM_APPL_CODE
# undef RTE_START_SEC_NVM_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef RTE_START_SEC_OHDSCANSLAVE_APPL_CODE
# undef RTE_START_SEC_OHDSCANSLAVE_APPL_CODE
#define START_SEC_CODE
#endif

#ifdef OHDSCanSlave_START_SEC_CODE
# undef OHDSCanSlave_START_SEC_CODE
#define START_SEC_CODE
#endif

#ifdef OHDSCanSlave_START_SEC_CONST_UNSPECIFIED
# undef OHDSCanSlave_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef OHDSCanSlave_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef OHDSCanSlave_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef OHDSCanSlave_START_SEC_VAR_INIT_UNSPECIFIED
# undef OHDSCanSlave_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#ifdef OHDSCanSlave_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef OHDSCanSlave_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#ifdef RTE_STOP_SEC_COMM_APPL_CODE
# undef RTE_STOP_SEC_COMM_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef RTE_STOP_SEC_CTAPHUFTPMSDIA_APPL_CODE
# undef RTE_STOP_SEC_CTAPHUFTPMSDIA_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSdia_STOP_SEC_CODE
# undef CtApHufTPMSdia_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSdia_STOP_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSdia_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CtApHufTPMSdia_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSdia_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSdia_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSdia_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSdia_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSdia_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_CTAPHUFTPMSMGR_APPL_CODE
# undef RTE_STOP_SEC_CTAPHUFTPMSMGR_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSmgr_STOP_SEC_CODE
# undef CtApHufTPMSmgr_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSmgr_STOP_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSmgr_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CtApHufTPMSmgr_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSmgr_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSmgr_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSmgr_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSmgr_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSmgr_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_CTAPHUFTPMSROE_APPL_CODE
# undef RTE_STOP_SEC_CTAPHUFTPMSROE_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSroe_STOP_SEC_CODE
# undef CtApHufTPMSroe_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSroe_STOP_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSroe_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CtApHufTPMSroe_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSroe_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSroe_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSroe_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSroe_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSroe_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_CTAPHUFTPMSWNH_APPL_CODE
# undef RTE_STOP_SEC_CTAPHUFTPMSWNH_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSwnh_STOP_SEC_CODE
# undef CtApHufTPMSwnh_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSwnh_STOP_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSwnh_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CtApHufTPMSwnh_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSwnh_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSwnh_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSwnh_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSwnh_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSwnh_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_CTAPHUFTPMSWPA_APPL_CODE
# undef RTE_STOP_SEC_CTAPHUFTPMSWPA_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSwpa_STOP_SEC_CODE
# undef CtApHufTPMSwpa_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtApHufTPMSwpa_STOP_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSwpa_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CtApHufTPMSwpa_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSwpa_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSwpa_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSwpa_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtApHufTPMSwpa_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSwpa_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_CTCDHUFTPMSRFD_APPL_CODE
# undef RTE_STOP_SEC_CTCDHUFTPMSRFD_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtCdHufTPMSrfd_STOP_SEC_CODE
# undef CtCdHufTPMSrfd_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef CtCdHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef CtCdHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtCdHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef CtCdHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_STOP_SEC_NVM_APPL_CODE
# undef RTE_STOP_SEC_NVM_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef RTE_STOP_SEC_OHDSCANSLAVE_APPL_CODE
# undef RTE_STOP_SEC_OHDSCANSLAVE_APPL_CODE
#define STOP_SEC_CODE
#endif

#ifdef OHDSCanSlave_STOP_SEC_CODE
# undef OHDSCanSlave_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#ifdef OHDSCanSlave_STOP_SEC_CONST_UNSPECIFIED
# undef OHDSCanSlave_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef OHDSCanSlave_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef OHDSCanSlave_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef OHDSCanSlave_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef OHDSCanSlave_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef OHDSCanSlave_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef OHDSCanSlave_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#ifdef RTE_START_SEC_CONST_DEFAULT_RTE_CDATA_GROUP_UNSPECIFIED
# undef RTE_START_SEC_CONST_DEFAULT_RTE_CDATA_GROUP_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#ifdef RTE_STOP_SEC_CONST_DEFAULT_RTE_CDATA_GROUP_UNSPECIFIED
# undef RTE_STOP_SEC_CONST_DEFAULT_RTE_CDATA_GROUP_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#ifdef RTE_START_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
# undef RTE_START_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#ifdef RTE_STOP_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
# undef RTE_STOP_SEC_VAR_DEFAULT_RTE_PIM_GROUP_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#if 0

#ifdef CtCdHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_START_SEC_CODE
# undef CtCdHufTPMSrfd_START_SEC_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef RTE_STOP_SEC_CTCDHUFTPMSRFD_APPL_CODE
# undef RTE_STOP_SEC_CTCDHUFTPMSRFD_APPL_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtCdHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_STOP_SEC_CODE
# undef CtCdHufTPMSrfd_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef CtCdHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
# undef CtCdHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#endif

#if 0

#ifdef RTE_START_SEC_CTCDHUFTPMSRFD_APPL_CODE
# undef RTE_START_SEC_CTCDHUFTPMSRFD_APPL_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_CONST_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_VAR_INIT_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_CODE
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_CONST_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#endif

#if 0

#ifdef RTE_STOP_SEC_CDD_OHDS_CLOCKSYNC_SLAVECAN_V1_APPL_CODE
# undef RTE_STOP_SEC_CDD_OHDS_CLOCKSYNC_SLAVECAN_V1_APPL_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_CODE
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef RTE_START_SEC_CDD_OHDS_CLOCKSYNC_SLAVECAN_V1_APPL_CODE
# undef RTE_START_SEC_CDD_OHDS_CLOCKSYNC_SLAVECAN_V1_APPL_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CDD_OHDS_ClockSync_SlaveCAN_V1_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef RTE_START_SEC_CTAPHUFTPMSRFD_APPL_CODE
# undef RTE_START_SEC_CTAPHUFTPMSRFD_APPL_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CtApHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CtApHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef RTE_STOP_SEC_CTAPHUFTPMSRFD_APPL_CODE
# undef RTE_STOP_SEC_CTAPHUFTPMSRFD_APPL_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
# undef CtApHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_STOP_SEC_CODE
# undef CtApHufTPMSrfd_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_START_SEC_CODE
# undef CtApHufTPMSrfd_START_SEC_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CtApHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
# undef CtApHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_START_SEC_CODE
# undef CpCdHufTPMSrfd_START_SEC_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
# undef CpCdHufTPMSrfd_STOP_SEC_VAR_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef RTE_START_SEC_CPCDHUFTPMSRFD_APPL_CODE
# undef RTE_START_SEC_CPCDHUFTPMSRFD_APPL_CODE
#define START_SEC_CODE
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
# undef CpCdHufTPMSrfd_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
# undef CpCdHufTPMSrfd_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CpCdHufTPMSrfd_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_STOP_SEC_CODE
# undef CpCdHufTPMSrfd_STOP_SEC_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
# undef CpCdHufTPMSrfd_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#define START_SEC_VAR_ZERO_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
# undef CpCdHufTPMSrfd_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST
#endif

#endif

#if 0

#ifdef RTE_STOP_SEC_CPCDHUFTPMSRFD_APPL_CODE
# undef RTE_STOP_SEC_CPCDHUFTPMSRFD_APPL_CODE
#define STOP_SEC_CODE
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
# undef CpCdHufTPMSrfd_START_SEC_VAR_INIT_UNSPECIFIED
#define START_SEC_VAR_INIT_UNSPECIFIED
#endif

#endif

#if 0

#ifdef CpCdHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
# undef CpCdHufTPMSrfd_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR
#endif

#endif

#ifndef SKIP_MAGIC_NUMBER
#ifdef RTE_MAGIC_NUMBER
#  if RTE_MAGIC_NUMBER != 1513305418
#error "The magic number of the generated file <C:/_TSS/DAG/MFA2/Target/Appl/GenData/Rte/Rte_MemMap.h> is different. Please check time and date of the generated RTE files!"
#endif
#else
#define RTE_MAGIC_NUMBER 1513305418
#endif
#endif

