#ifndef _RTE_COMPILER_CFG_H
#define _RTE_COMPILER_CFG_H

#define Test_LOG_ENABLE
#define USE_VEH_DIR_INFO 0U
#define ABS_SIG_SIZE_ONEBYTE 1U
#define _M_IX86
#define ECU_SHUTDOWN_ENABLE 1U
#define Gildas_Debug_Warnung 0U
#define E2E_ENABLE 1U
#define RE_SIMULATION_ENABLE 1U
#define RTE_CODE
#define RTE_VAR_NOINIT
#define RTE_VAR_ZERO_INIT
#define RTE_VAR_INIT
#define RTE_CONST
#define RTE_APPL_DATA
#define RTE_APPL_VAR
#define RTE_APPL_CODE
#define RTE_COMM_APPL_VAR
#define RTE_COMM_APPL_DATA
#define RTE_COMM_APPL_CODE
#define RTE_COMM_APPL_CONST
#define RTE_CTAPHUFTPMSDIA_APPL_VAR
#define RTE_CTAPHUFTPMSDIA_APPL_DATA
#define RTE_CTAPHUFTPMSDIA_APPL_CODE
#define RTE_CTAPHUFTPMSDIA_APPL_CONST
#define CtApHufTPMSdia_CODE
#define CtApHufTPMSdia_CONST
#define CtApHufTPMSdia_VAR_NOINIT
#define CtApHufTPMSdia_VAR_INIT
#define CtApHufTPMSdia_VAR_ZERO_INIT
#define RTE_CTAPHUFTPMSMGR_APPL_VAR
#define RTE_CTAPHUFTPMSMGR_APPL_DATA
#define RTE_CTAPHUFTPMSMGR_APPL_CODE
#define RTE_CTAPHUFTPMSMGR_APPL_CONST
#define CtApHufTPMSmgr_CODE
#define CtApHufTPMSmgr_CONST
#define CtApHufTPMSmgr_VAR_NOINIT
#define CtApHufTPMSmgr_VAR_INIT
#define CtApHufTPMSmgr_VAR_ZERO_INIT
#define RTE_CTAPHUFTPMSROE_APPL_VAR
#define RTE_CTAPHUFTPMSROE_APPL_DATA
#define RTE_CTAPHUFTPMSROE_APPL_CODE
#define RTE_CTAPHUFTPMSROE_APPL_CONST
#define CtApHufTPMSroe_CODE
#define CtApHufTPMSroe_CONST
#define CtApHufTPMSroe_VAR_NOINIT
#define CtApHufTPMSroe_VAR_INIT
#define CtApHufTPMSroe_VAR_ZERO_INIT
#define RTE_CTAPHUFTPMSWNH_APPL_VAR
#define RTE_CTAPHUFTPMSWNH_APPL_DATA
#define RTE_CTAPHUFTPMSWNH_APPL_CODE
#define RTE_CTAPHUFTPMSWNH_APPL_CONST
#define CtApHufTPMSwnh_CODE
#define CtApHufTPMSwnh_CONST
#define CtApHufTPMSwnh_VAR_NOINIT
#define CtApHufTPMSwnh_VAR_INIT
#define CtApHufTPMSwnh_VAR_ZERO_INIT
#define RTE_CTAPHUFTPMSWPA_APPL_VAR
#define RTE_CTAPHUFTPMSWPA_APPL_DATA
#define RTE_CTAPHUFTPMSWPA_APPL_CODE
#define RTE_CTAPHUFTPMSWPA_APPL_CONST
#define CtApHufTPMSwpa_CODE
#define CtApHufTPMSwpa_CONST
#define CtApHufTPMSwpa_VAR_NOINIT
#define CtApHufTPMSwpa_VAR_INIT
#define CtApHufTPMSwpa_VAR_ZERO_INIT
#define RTE_CTCDHUFTPMSRFD_APPL_VAR
#define RTE_CTCDHUFTPMSRFD_APPL_DATA
#define RTE_CTCDHUFTPMSRFD_APPL_CODE
#define RTE_CTCDHUFTPMSRFD_APPL_CONST
#define CtCdHufTPMSrfd_CODE
#define CtCdHufTPMSrfd_CONST
#define CtCdHufTPMSrfd_VAR_NOINIT
#define CtCdHufTPMSrfd_VAR_INIT
#define CtCdHufTPMSrfd_VAR_ZERO_INIT
#define RTE_NVM_APPL_VAR
#define RTE_NVM_APPL_DATA
#define RTE_NVM_APPL_CODE
#define RTE_NVM_APPL_CONST
#define RTE_OHDSCANSLAVE_APPL_VAR
#define RTE_OHDSCANSLAVE_APPL_DATA
#define RTE_OHDSCANSLAVE_APPL_CODE
#define RTE_OHDSCANSLAVE_APPL_CONST
#define OHDSCanSlave_CODE
#define OHDSCanSlave_CONST
#define OHDSCanSlave_VAR_NOINIT
#define OHDSCanSlave_VAR_INIT
#define OHDSCanSlave_VAR_ZERO_INIT
#define RTE_CONST_DEFAULT_RTE_CDATA_GROUP
#define RTE_VAR_DEFAULT_RTE_PIM_GROUP

#ifndef SKIP_MAGIC_NUMBER
#ifdef RTE_MAGIC_NUMBER
#if RTE_MAGIC_NUMBER != 1513305418
#error "The magic number of the generated file <C:/_TSS/DAG/MFA2/Target/Appl/GenData/Rte/Rte_Compiler_Cfg.h> is different. Please check time and date of the generated RTE files!"
#endif
#else
#define RTE_MAGIC_NUMBER 1513305418
#endif
#endif

#endif
